### ISSUE TITLE
Dialogue element clean-up: `$#...`

### ISSUE THREAD

**Issue by ebeshero** [gak5275/StardewDIGIT210#6]
Here are some clean-up things you can do your XML files as you're developing them. We found some regex patterns of special characters that we can remove from dialogue elements that should clean up your analysis work! 

`(\$|#)\w+?(\$|#)`

This looks for, either a literal `$` or a `#` and any alphanumeric characters up to another literal `$` or a `#`. (This catches them in either order). You can search and replace with nothing, very carefully across files! 

This doesn't pick up everything, but you can pick up more afterwards, with something like:

`\w(\$|#)`

Keep looking for `#` and `\$` to find more of these...

**Comment by WillStill** [comment]
Found another part of doc cleanup that we might want to talk about.

Some of the `dialogue` elements in the xml hold text that describes the day of week and number, similarly to `content`. This example comes from `Alex.xml`, line 39:
```xml
<p>
<context>Wed:</context>
<dialogue>"Looks like a good day to play catch, huh? 
$q 5/6 Wed_01_old#I'd ask you to throw the ball around, but you don't really seem like the sports type.^If you weren't a girl I'd ask you to play catch.
#$r 6 0 Wed_01_02#I'm fine just watching you from a distance.
#$r 5 15 Wed_01_01#I want to play catch with you!
#$r 5 0 Wed_01_03#(angry) What's that supposed to mean?"
</dialogue> #!String
</p>
```

Do we want to approach this by removing everything inside the `#`s or could we create more `dialogue` elements?

**Comment by gak5275** [comment]
I think those indicate the different options the player can respond with. I have noticed that "#$r" usually precedes a player choice. We could probably remove the dates, since they don't seem that important to the dialogue.

Actually, since we are not including player dialogue, we might just want to remove those entire lines and keep only the question being asked.

**Comment by gak5275** [comment]
A character asking a question might be indicated by "$q".
